codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes
    after_n_builds: 2  # Espera tanto el build de frontend como backend

coverage:
  precision: 2
  round: down
  range: "70...100"
  
  status:
    project:
      default:
        target: 80%    # Cobertura mínima requerida
        threshold: 2%   # Permite una caída máxima de 2%
    patch:
      default:
        target: 85%    # Cobertura mínima para código nuevo
        threshold: 0%   # No permite caídas en código nuevo

  notify:
    slack:
      default:
        url: "${SLACK_WEBHOOK}"
        threshold: 1%
        only_pulls: false
        branches:
          - main
          - develop
        message: "Coverage {{changed}} for {{owner}}/{{repo}}"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no
  require_base: no
  require_head: yes
  after_n_builds: 2

ignore:
  - "tests/**/*"      # Ignora archivos de test
  - "**/*.test.ts"    # Ignora archivos de test de TypeScript
  - "**/*.spec.ts"    # Ignora archivos de test de TypeScript
  - "**/migrations/*" # Ignora archivos de migración
  - "**/static/**/*" # Ignora archivos estáticos
