"""initial migration

Revision ID: 2024_07_initial_migration
Revises: 
Create Date: 2024-12-14 08:29:55.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2024_07_initial_migration'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('properties',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('UTC', current_timestamp)"), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('UTC', current_timestamp)"), nullable=True),
        sa.Column('name', sa.String(length=255), nullable=True),
        sa.Column('address', sa.String(length=255), nullable=False),
        sa.Column('city', sa.String(length=100), nullable=True),
        sa.Column('state', sa.String(length=100), nullable=True),
        sa.Column('zip_code', sa.String(length=20), nullable=True),
        sa.Column('bedrooms', sa.Integer(), nullable=True),
        sa.Column('bathrooms', sa.Integer(), nullable=True),
        sa.Column('status', sa.String(length=50), server_default='available', nullable=True),
        sa.Column('is_active', sa.Boolean(), server_default='true', nullable=True),
        sa.Column('property_type', sa.String(length=50), nullable=False),
        sa.Column('parent_property_id', sa.Integer(), nullable=True),
        sa.Column('user_id', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(['parent_property_id'], ['properties.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.CheckConstraint("property_type IN ('PRINCIPAL', 'UNIT')", name='check_property_type'),
        sa.CheckConstraint("status IN ('available', 'rented') OR status IS NULL", name='check_status')
    )
    op.create_index(op.f('ix_properties_id'), 'properties', ['id'], unique=False)
    op.create_index(op.f('ix_properties_user_id'), 'properties', ['user_id'], unique=False)

    op.create_table('tenants',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('first_name', sa.String(), nullable=False),
        sa.Column('last_name', sa.String(), nullable=False),
        sa.Column('property_id', sa.Integer(), nullable=False),
        sa.Column('lease_start', sa.Date(), nullable=False),
        sa.Column('lease_end', sa.Date(), nullable=False),
        sa.Column('deposit', sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column('monthly_rent', sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column('payment_day', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.CheckConstraint('payment_day BETWEEN 1 AND 31', name='check_payment_day')
    )
    op.create_index(op.f('ix_tenants_id'), 'tenants', ['id'], unique=False)
    op.create_index(op.f('ix_tenants_property_id'), 'tenants', ['property_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenants_property_id'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_id'), table_name='tenants')
    op.drop_table('tenants')
    op.drop_index(op.f('ix_properties_user_id'), table_name='properties')
    op.drop_index(op.f('ix_properties_id'), table_name='properties')
    op.drop_table('properties')
    # ### end Alembic commands ###
