"""add_property_type_and_parent_id

Revision ID: 5fa6c40413c1
Revises: 15a1557fbd3b
Create Date: 2024-11-29 20:41:27.722750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fa6c40413c1'
down_revision = '15a1557fbd3b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the enum type first
    propertytype = sa.Enum('PRINCIPAL', 'UNIT', name='propertytype')
    propertytype.create(op.get_bind())
    
    # Add the columns as nullable first
    op.add_column('properties', sa.Column('property_type', propertytype, nullable=True))
    op.add_column('properties', sa.Column('parent_property_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'properties', 'properties', ['parent_property_id'], ['id'])
    
    # Update existing rows
    op.execute("UPDATE properties SET property_type = 'PRINCIPAL'")
    
    # Make property_type non-nullable
    op.alter_column('properties', 'property_type',
                    existing_type=propertytype,
                    nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the constraints and columns
    op.drop_constraint(None, 'properties', type_='foreignkey')
    op.drop_column('properties', 'parent_property_id')
    op.drop_column('properties', 'property_type')
    
    # Drop the enum type
    sa.Enum(name='propertytype').drop(op.get_bind())
    # ### end Alembic commands ###
