"""add_updated_at_default

Revision ID: f72fb7c46105
Revises: 710596404494
Create Date: 2024-11-28 02:48:47.701446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f72fb7c46105'
down_revision = '710596404494'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
